### ISSUE TITLE
Getting strange errors when trying to execute in scope of pipeline

### ISSUE THREAD

**Issue by akuryan** [Nightapes/go-semantic-release#72]
I'm trying to execute go-semantic-release from docker image in my gitlab CI pipeline.
I am getting strange error:
```
Using docker image sha256:181cf62eeefdfa3138f0dba256e5583f770f747f0b593d7953eec17acc0469a1 for nightapes/go-semantic-release:latest with digest nightapes/go-semantic-release@sha256:9e362ff31e0a126a928ba3822f06201a2b60bdded2c4988d2f9eacef61ba3290 ...
Error: unknown command "sh" for "go-semantic-release"
Did you mean this?
	set
Run 'go-semantic-release --help' for usage.
```

Here is my pipeline description:
```
semver:
  stage: semver
  image:
    name: nightapes/go-semantic-release:latest
  script:
    - go-semantic-release next
  only:
    refs:
      - master
      - semantic-versioning
      - deploy
```

**Comment by fwiedmann** [comment]
Hey @akuryan,

thanks for asking and maybe it is not 100% clear about how to use go-semantic-release.

You have to options:

1. instead of calling the complete command with `go-semantic-release` prefix, you can just use the sub commands like `next`. This works because the tool it selfs is set as entrypoint in the `Dockerfile`.

2. Option two is to overwrite the image entrypoint in your `.gitlab-ci.yml`

https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#available-settings-for-image

**Comment by akuryan** [comment]
I updated my ci yml:
```
semver:
  stage: semver
  image:
    name: nightapes/go-semantic-release:latest
  script:
    - next
  only:
    refs:
      - master
      - semantic-versioning
      - deploy
  artifacts:
    expire_in: 1h
    reports:
      dotenv: build.env
```
Still, getting an error:
```
Using docker image sha256:181cf62eeefdfa3138f0dba256e5583f770f747f0b593d7953eec17acc0469a1 for nightapes/go-semantic-release:latest with digest nightapes/go-semantic-release@sha256:9e362ff31e0a126a928ba3822f06201a2b60bdded2c4988d2f9eacef61ba3290 ...
Error: unknown command "sh" for "go-semantic-release"
Did you mean this?
	set
Run 'go-semantic-release --help' for usage.
```

**Comment by fwiedmann** [comment]
Thanks for trying option 1. As I understand GitLab tries to run all commands in the `script` array with e.g. `sh 'next'` (using`sh` as prefix).

To integrate `go-semantic-release` in your GitLab CI, I will have to update our Docker image.

After this change, you will have to update the CI with my second proposed option. But I will add GitLab CI/CD usage to our docs.

**Comment by akuryan** [comment]
Thank you
I am waiting for this with impatience.
Can I help somehow?

**Comment by fwiedmann** [comment]
@akuryan check out the example gitlab-ci in the example folder.

**Comment by fwiedmann** [comment]
please try with this image `nightapes/go-semantic-release:development-1.16`

**Comment by fwiedmann** [comment]
@Nightapes due to my changes did not trigger a new release, the current latest and 2.0.0 were not updated with.

Could you update these versions?

**Comment by Nightapes** [comment]
@akuryan  Please try version `nightapes/go-semantic-release:2.0.1`

**Comment by akuryan** [comment]
Hi
```
semver:
  stage: semver
  image:
    name: nightapes/go-semantic-release:2.0.1
  script:
    - next
  only:
    refs:
      - master
      - semantic-versioning
      - deploy
  artifacts:
    expire_in: 1h
    reports:
      dotenv: build.env
```

Fails still with 
```
Using docker image sha256:aed3858e0a9bf96fc2316a26ff1dbf72c0ad3e1f8418c6e41343729a0f4028b8 for nightapes/go-semantic-release:2.0.1 with digest nightapes/go-semantic-release@sha256:17bdfbca6d17bc479534d8e9e62782c9a27a7378fe7a1b93beedd037daa70750 ...
Error: unknown command "sh" for "go-semantic-release"
Did you mean this?
	set
Run 'go-semantic-release --help' for usage.
```

Also I tried 
```
semver:
  stage: semver
  image:
    name: nightapes/go-semantic-release:2.0.1
  script:
    - go-semantic-release next
  only:
    refs:
      - master
      - semantic-versioning
      - deploy
  artifacts:
    expire_in: 1h
    reports:
      dotenv: build.env
```

with same result
```
Using docker image sha256:aed3858e0a9bf96fc2316a26ff1dbf72c0ad3e1f8418c6e41343729a0f4028b8 for nightapes/go-semantic-release:2.0.1 with digest nightapes/go-semantic-release@sha256:17bdfbca6d17bc479534d8e9e62782c9a27a7378fe7a1b93beedd037daa70750 ...
Error: unknown command "sh" for "go-semantic-release"
Did you mean this?
	set
Run 'go-semantic-release --help' for usage.
```

**Comment by fwiedmann** [comment]
Hey @akuryan,

in the hurry yesterday, I forgot to add the entrypoint overwrite. Pls checkout the changes in #75

**Comment by fwiedmann** [comment]
try this
```
semver:
  stage: semver
  image:
    name: nightapes/go-semantic-release:2.0.1
    entrypoint: ["/bin/sh"]
  script:
    - go-semantic-release next
  only:
    refs:
      - master
      - semantic-versioning
      - deploy
  artifacts:
    expire_in: 1h
    reports:
      dotenv: build.env
```

**Comment by akuryan** [comment]
it says now:
```
Using docker image sha256:aed3858e0a9bf96fc2316a26ff1dbf72c0ad3e1f8418c6e41343729a0f4028b8 for nightapes/go-semantic-release:2.0.1 with digest nightapes/go-semantic-release@sha256:17bdfbca6d17bc479534d8e9e62782c9a27a7378fe7a1b93beedd037daa70750 ...
/bin/sh: can't open 'sh': No such file or directory
```

**Comment by fwiedmann** [comment]
so after playing around with gitlab, I finally managed to get it working:

```
semver:
  stage: semver
  image:
    name: nightapes/go-semantic-release:2.0.1
    entrypoint: [""]
  script:
    - go-semantic-release next
  only:
    refs:
      - master
      - semantic-versioning
      - deploy
  artifacts:
    expire_in: 1h
    reports:
      dotenv: build.env
```

**Comment by fwiedmann** [comment]
I tried it myself in a Gitlab instance, and it worked fine:
```
Getting source from Git repository
00:00
Using docker image sha256:9492c703c6ff7827ee20e22745161a2e21f399dfc83f3d51b2d9274bb6029903 for gitlab/gitlab-runner-helper:x86_64-7a6612da with digest gitlab/gitlab-runner-helper@sha256:baf514070e725460058d2ce5c348745bd8083d6ea82e43ef7ddf6022c9ea06da ...
Fetching changes...
Initialized empty Git repository in /builds/felix.wiedmann/test/.git/
Created fresh repository.
Checking out aa8176c7 as master...
Skipping Git submodules setup
Executing "step_script" stage of the job script
00:01
Using docker image sha256:aed3858e0a9bf96fc2316a26ff1dbf72c0ad3e1f8418c6e41343729a0f4028b8 for nightapes/go-semantic-release:latest with digest nightapes/go-semantic-release@sha256:17bdfbca6d17bc479534d8e9e62782c9a27a7378fe7a1b93beedd037daa70750 ...
$ go-semantic-release next
1.0.0
Job succeeded
```

**Comment by fwiedmann** [comment]
This is my CI config

```yaml
stages:
  - release

release:
  stage: release
  image:
    name: nightapes/go-semantic-release:latest
    entrypoint: [""]
  script:
    - go-semantic-release next
  only:
    - master
```
