### ISSUE TITLE
Error: could not get commits object not found 🤔 

### ISSUE THREAD

**Issue by t-h-o** [Nightapes/go-semantic-release#78]
Unfortunately, I'm having difficulty running this for the first time on a new repository.

`release.yml`
```yaml
name: release

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      ...
  
  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: binaries

      - name: Login to Github registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      
      - name: Install semantic-release
        run: |
          wget https://github.com/Nightapes/go-semantic-release/releases/download/v2.0.1/go-semantic-release.linux_x86_64.zip
          unzip go-semantic-release.linux_x86_64.zip
          chmod +x go-semantic-release.linux_x86_64
      
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          ls
          ./go-semantic-release.linux_x86_64 release --loglevel trace
```

`.release.yml`
```yaml
release: github
github:
  repo: stewartgo
  user: t-h-o
commitFormat: conventional
branch:
  main: release
assets:
  - path: stewart.linux_x86_64
    compress: false
  - path: stewart.windows_x86_64.exe
    compress: false
changelog:
  docker:
    latest: true
    repository: "ghcr.io/t-h-o/stewart"
hooks:
  preRelease:
    - make docker-build -e VERSION=$RELEASE_VERSION
  postRelease:
    - make docker-push
```

`Output`
```
Dockerfile
Makefile
cmd
config
go-semantic-release.linux_x86_64
go-semantic-release.linux_x86_64.zip
go.mod
go.sum
internal
main.go
stewart.linux_x86_64
stewart.windows_x86_64.exe
time="2021-09-27T05:52:48Z" level=trace msg="Found config release: github\ngithub:\n  repo: stewartgo\n  user: t-h-o\ncommitFormat: conventional\nbranch:\n  main: release\nassets:\n  - path: stewart.linux_x86_64\n    compress: false\n  - path: stewart.windows_x86_64.exe\n    compress: false\nchangelog:\n  docker:\n    latest: true\n    repository: \"ghcr.io/t-h-o/stewart\"\nhooks:\n  preRelease:\n    - make docker-build -e VERSION=$RELEASE_VERSION\n  postRelease:\n    - make docker-push\n"
time="2021-09-27T05:52:48Z" level=trace msg="Found config &{CommitFormat:conventional Branch:map[main:release] Analyzer:{TokenSeparators:[]} Changelog:{PrintAll:false TemplateTitle: TemplatePath: Docker:{Latest:true Repository:ghcr.io/t-h-o/stewart} NPM:{Repository: PackageName:}} Release:github GitHubProvider:{Repo:stewartgo User:t-h-o CustomURL: AccessToken: TagPrefix:<nil>} GitLabProvider:{Repo: CustomURL: AccessToken: TagPrefix:<nil>} GitProvider:{Email: Username: Auth: SSH:false TagPrefix:<nil>} Assets:[{Path:stewart.linux_x86_64 Rename: Name: Compress:false} {Path:stewart.windows_x86_64.exe Rename: Name: Compress:false}] Checksum:{Algorithm:} Hooks:{PreRelease:[make docker-build -e VERSION=$RELEASE_VERSION] PostRelease:[make docker-push]} Integrations:{NPM:{Enabled:false Path:}} ReleaseTitle: IsPreRelease:false}"
time="2021-09-27T05:52:48Z" level=debug msg="Commit format set to conventional"
time="2021-09-27T05:52:48Z" level=debug msg="initialize new github-provider"
time="2021-09-27T05:52:48Z" level=debug msg="check if GITHUB_TOKEN environment variable is set"
time="2021-09-27T05:52:48Z" level=debug msg="not running on travis"
time="2021-09-27T05:52:48Z" level=debug msg="GITHUB_EVENT_NAME=push, not running on pr"
time="2021-09-27T05:52:48Z" level=info msg="Found CI: GithubActions CI"
time="2021-09-27T05:52:48Z" level=trace msg="Found CI config: &{IsPR:false PR: PRBranch: Branch:main Tag: Commit:c29fee211db5142fac6d9bcaaaf88642a886a1f9 BuildURL: Service:GithubActions Name:GithubActions CI}"
time="2021-09-27T05:52:48Z" level=debug msg="Ignore .version file if exits, false"
time="2021-09-27T05:52:48Z" level=warning msg="Could not read cache .version, will ignore cache"
time="2021-09-27T05:52:48Z" level=debug msg="Found no tags"
time="2021-09-27T05:52:48Z" level=info msg="This is the first release, will set version to 1.0.0"
time="2021-09-27T05:52:48Z" level=debug msg="Could not get next version"
Error: could not get commits object not found
```

I see that it's failing on line [109 in `semantic-release.go`](https://github.com/Nightapes/go-semantic-release/blob/ec8dc17df2ddce39b32c7784a9da31ec22a67f00/pkg/semanticrelease/semantic-release.go#L109), but I'm not sure why? Any pointers?

**Comment by t-h-o** [comment]
I figured it out. `actions/checkout@v2` changed the default fetch functionality. It fetches only a [single commit](https://github.com/actions/checkout#whats-new). 

Adding the `fetch-depth: 0` value fixes this issue.
```yaml
- name: Checkout
  uses: actions/checkout@v2
  with:
    fetch-depth: 0
```
