### ISSUE TITLE
Error: could not get commits object not found gitlab-ci.yml

### ISSUE THREAD

**Issue by abdullahtoraman** [Nightapes/go-semantic-release#81]
Hello,

It hits error when pipeline runs. I have already set GITLAB_ACCESS_TOKEN env in CI/CD environment settings.

Here is the .release.yml
```
commitFormat: conventional
branch:
  dev: release
release: 'gitlab'
gitlab:
  repo: "<repo_name>"
```

Here is the .gitlab-ci.yml
```
deploy-release-management:
  stage: deploy-release-management
  environment:
    name: test
  only:
    refs:
      - dev
  image:
    name: nightapes/go-semantic-release:latest
    entrypoint: [""]
  script:
    - go-semantic-release next
```

Here is the pipeline job logs.
```
Using docker image sha256:a94f6e1d7067e24eae9349ee954af5324b4e7ee8483d9bff17fe264456b1e362 for nightapes/go-semantic-release:latest with digest nightapes/go-semantic-release@sha256:a0fe6d7c099e90eadbcd144a23b4cf07caca883062747b5710455e520f880895 ...
$ go-semantic-release next
Error: could not get commits object not found
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: exit code 1
```

How can we resolve this issue ?

Thanks.

**Comment by fwiedmann** [comment]
Hey hey, can you check your CI/CD settings for the following config:

Should be set to '0'

https://docs.gitlab.com/ee/ci/pipelines/settings.html

**Comment by abdullahtoraman** [comment]
Hello,

I set it to '0' but it did not solve problem. I got same error message.

Thanks.

**Comment by fwiedmann** [comment]
Thanks for checking. On which branch do you exec the Pipeline?

**Comment by abdullahtoraman** [comment]
branch name is not main and dev. I created branch from main for test this pipeline.

**Comment by abdullahtoraman** [comment]
Hello,

Is there any comment ?

Thanks.

**Comment by Nightapes** [comment]
When your Branch name is not main or dev you need to update the config

```
commitFormat: conventional
branch:
  <your_branch_name>: release
release: 'gitlab'
gitlab:
  repo: "<repo_name>"
```

Do you have an example repository to check the issue?

**Comment by abdullahtoraman** [comment]
Actually, i sent wrong conf file. Here is my config.

```
commitFormat: conventional
branch:
  RLP-503-release-management: release
release: 'gitlab'
gitlab:
  repo: "<repo_name>"
```
I do not have an example repository. It works when i build and run from source repo by the way. It did not work in gitlab pipeline.
